#!/bin/bash

if [[ ! -e .devcontainer ]]; then
  echo this repository does not have devcontainer configuration file.
  exit 1
fi

DEVC_JSON=$(cat .devcontainer/devcontainer.json | strip-json-comments)
SERVICE_NAME=$(echo $DEVC_JSON | jq -r .service)
WORKDIR_NAME=$(basename $(pwd))

DEVCONTAINER_SSH_AUTH_SOCK=/tmp/devcontainer-ssh-auth-sock
ln -f ${SSH_AUTH_SOCK} ${DEVCONTAINER_SSH_AUTH_SOCK}

DEVCONTAINER_FLAGS=""
if [[ ! -z $(docker ps -f name=${WORKDIR_NAME}_devcontainer-${SERVICE_NAME}-1 -q) ]]; then
  DEVCONTAINER_FLAGS="--expect-existing-container=true "
fi
REMOVE_FLAG=""
if [ "$1" = "true" ]; then
    REMOVE_FLAG="--remove-existing-container"
fi

devcontainer up ${DEVCONTAINER_FLAGS} ${REMOVE_FLAG} \
  --mount "type=bind,source=$(pwd),target=/workspaces/${WORKDIR_NAME}" \
  --mount "type=bind,source=${DEVCONTAINER_SSH_AUTH_SOCK},target=/home/vscode/.ssh-auth-sock" \
  --remote-env SSH_AUTH_SOCK=/home/vscode/.ssh-auth-sock \
  --additional-features '{"ghcr.io/goropikari/devcontainer-feature/neovim:latest": {}}'
